### ISSUE TITLE
Moving from Python to Bash

### ISSUE THREAD

**Issue by notkaramel** [notkaramel/ArchLinux-on-ARM#3]
I'm seeing the logic and function call can easily be called using `bash` (or `sh`) insteaad of Python. Not really sure how beneficial that would be, the host machine currently has to be Linux for the program to work anyways

**Comment by lokeshgit1711** [comment]
I could not understand your issue clearly. But, In order to invoke a python script from bash
1.  Make sure Python software installed in the Linux OS. if not install using below command
     1.1 yum(centos or Redhat) or apt(Debain,ubuntu) 
             yum install python3
             apt install python3
3.  You can invoke  python script(python_script.py) from bash file (bash_file.sh) or by a function created inside .bashrc file present in your user home path. I have explained the same in point 4 and point 5
4. create a bash file( bash_file.sh )  and invoke python script by providing its absolute path
      #!/bin/bash
      python3 /path/to/script/python_script.py
      
5. You can also write a bash function and initialize that in .bashrc file.  So whenever you invoke the bash function. it will invoke the Python script(Like alias)
       
       4.1 open ~/.bashrc file (for BASH SHELL) and write the function
              invoke_python () {
                     python3 /path/to/script/python_script.py
              }
       
        4.2 Logout/login or run .bashrc
        4.3 Now, you can directly call the function "invoke_python" from the BASH terminal. this will invoke your python script in the background

**Comment by notkaramel** [comment]
Apologies for being unclear, and also that's not really my idea. Seeing the Python file is mostly using `os.system` and `os.subsystem` to run stuff while other commands are just if's and print's, I'm suggesting rewrite the script in bash.

Thanks for your suggestion, albeit I will not proceed in that direction for the project.
